### ISSUE TITLE
Now that the website is ready, can we delete this repo?

### ISSUE THREAD

**Issue by dinocosta** [cesium/cesium.github.io#2]

**Comment by martinhoaragao** [comment]
I do not agree. This is useful as a coming soon landing page. Perhaps change the name of the repo?
For instance it's actually going to be used for SEI's coming soon.

**Comment by frm** [comment]
Don't we have a different Coming Soon for SEI as well?

**Comment by martinhoaragao** [comment]
I don't recall it. And I think this one would suit very well with SEI's design.

**Comment by frm** [comment]
We also have the [badass stellar one](http://cesium.github.io/sei16/). I'm fine with either.

**Comment by martinhoaragao** [comment]
Oh, nevermind. I thought this was the stellar one. 🙄 
I don't think there's a need to delete it though.

**Comment by frm** [comment]
I would make the suggestion of renaming both repos then. Something like `landing.cesium` and `landing.sei`, so we can deploy them as subdomains if we ever want to (and I think we should)

**Comment by dinocosta** [comment]
@frmendes Good suggestion! Already changed the name of this one but I cannot change the one for SEI, can you do it @martinhoaragao ?

**Comment by frm** [comment]
Renamed it. Also renamed the 2016 and 2015 websites to match the intranet pattern:

<img width="672" alt="screen shot 2016-10-23 at 00 10 49" src="https://cloud.githubusercontent.com/assets/4325027/19623110/5437746a-98b5-11e6-869d-7fc455bea5a8.png">

Should we close this?

**Comment by dinocosta** [comment]
@frmendes Thanks! Yes, will close it now 👍

**Comment by martinhoaragao** [comment]
Maybe teaser instead of landing?
I don’t get why we need name.something for the subdomain. Github’s would do
cesium.github.io/landingsei anything else is DNS side right?

On 22 October 2016 at 19:39:35, Fernando Mendes (notifications@github.com)
wrote:

I would make the suggestion of renaming both repos then. Something like
landing.cesium and landing.sei, so we can deploy them as subdomains if we
ever want to (and I think we should)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/cesium/CeSIUM-Temp-Website/issues/2#issuecomment-255546065,
or mute the thread
